language: java

dist: trusty

jdk:
- oraclejdk8

sudo: false

script:
- "mvn evosuite:generate"
- "mvn evosuite:export"
- "mvn cobertura:cobertura"
- "mvn evosuite:info"
- "mvn test"
- bash <(curl -s https://codecov.io/bash)
