/*
 * This file was automatically generated by EvoSuite
 * Mon Apr 18 02:38:09 GMT 2022
 */

package com.uh.pat;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.uh.pat.AVLTree;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class AVLTree_ESTest extends AVLTree_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      AVLTree aVLTree0 = new AVLTree();
      aVLTree0.insert(2157);
      aVLTree0.height();
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      AVLTree aVLTree0 = new AVLTree();
      int int0 = (-1634);
      aVLTree0.delete((-1634));
      aVLTree0.height();
      aVLTree0.delete(0);
      aVLTree0.find((-1));
      aVLTree0.delete((-1634));
      aVLTree0.insert((-1));
      aVLTree0.delete((-1634));
      int int1 = 0;
      aVLTree0.delete(0);
      aVLTree0.delete(1273);
      int int2 = 0;
      aVLTree0.insert(0);
      AVLTree.Node aVLTree_Node0 = aVLTree0.find(0);
      aVLTree0.find(0);
      aVLTree_Node0.height = 1;
      // Undeclared exception!
      try { 
        aVLTree0.delete((-987));
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.uh.pat.AVLTree", e);
      }
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      AVLTree aVLTree0 = new AVLTree();
      aVLTree0.getRoot();
      aVLTree0.getRoot();
      aVLTree0.getBalance((AVLTree.Node) null);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      AVLTree aVLTree0 = new AVLTree();
      aVLTree0.insert((-3126));
      AVLTree.Node aVLTree_Node0 = aVLTree0.getRoot();
      aVLTree_Node0.height = (-3126);
      aVLTree0.getBalance(aVLTree_Node0);
      AVLTree.Node aVLTree_Node1 = aVLTree0.find((-3126));
      int int0 = 0;
      aVLTree_Node1.key = 0;
      AVLTree aVLTree1 = new AVLTree();
      AVLTree.Node aVLTree_Node2 = aVLTree1.new Node((-3126));
      aVLTree_Node1.right = aVLTree_Node2;
      aVLTree_Node2.height = (-3126);
      int int1 = 1;
      aVLTree_Node1.key = 1;
      aVLTree0.getBalance(aVLTree_Node1);
      aVLTree0.getBalance(aVLTree_Node1);
      int int2 = (-1059);
      aVLTree_Node0.height = (-1059);
      // Undeclared exception!
      try { 
        aVLTree0.insert(0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.uh.pat.AVLTree", e);
      }
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      AVLTree aVLTree0 = new AVLTree();
      int int0 = 0;
      aVLTree0.insert(0);
      aVLTree0.delete(1);
      aVLTree0.delete(0);
      aVLTree0.insert(1);
      int int1 = 0;
      aVLTree0.insert(0);
      int int2 = 0;
      aVLTree0.delete(0);
      aVLTree0.find(0);
      aVLTree0.delete((-748));
      aVLTree0.insert(0);
      aVLTree0.delete(547);
      // Undeclared exception!
      try { 
        aVLTree0.insert(0);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // duplicate Key!
         //
         verifyException("com.uh.pat.AVLTree", e);
      }
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      AVLTree aVLTree0 = new AVLTree();
      int int0 = 0;
      aVLTree0.delete(0);
      int int1 = 0;
      aVLTree0.insert(0);
      AVLTree.Node aVLTree_Node0 = aVLTree0.getRoot();
      AVLTree.Node aVLTree_Node1 = aVLTree0.getRoot();
      aVLTree_Node1.right = aVLTree_Node0;
      aVLTree0.getBalance(aVLTree_Node1);
      // Undeclared exception!
      aVLTree0.find(1);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      AVLTree aVLTree0 = new AVLTree();
      aVLTree0.delete(0);
      aVLTree0.delete((-3138));
      aVLTree0.insert(0);
      aVLTree0.delete((-2200));
      aVLTree0.insert((-2464));
      // Undeclared exception!
      try { 
        aVLTree0.delete(0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      AVLTree aVLTree0 = new AVLTree();
      aVLTree0.insert(911);
      aVLTree0.insert(0);
      aVLTree0.delete(0);
      aVLTree0.insert((-1));
      aVLTree0.insert(0);
      // Undeclared exception!
      try { 
        aVLTree0.insert(0);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // duplicate Key!
         //
         verifyException("com.uh.pat.AVLTree", e);
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      AVLTree aVLTree0 = new AVLTree();
      aVLTree0.delete(1);
      aVLTree0.insert(4066);
      // Undeclared exception!
      try { 
        aVLTree0.insert(4066);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // duplicate Key!
         //
         verifyException("com.uh.pat.AVLTree", e);
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      AVLTree aVLTree0 = new AVLTree();
      aVLTree0.insert((-871));
      aVLTree0.insert(2416);
      aVLTree0.insert((-601));
      aVLTree0.height();
      aVLTree0.find((-137));
      aVLTree0.find(1);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      AVLTree aVLTree0 = new AVLTree();
      aVLTree0.insert(822);
      aVLTree0.find(1486);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      AVLTree aVLTree0 = new AVLTree();
      aVLTree0.insert(1759);
      aVLTree0.delete(1759);
      aVLTree0.insert(1759);
      int int0 = (-1);
      aVLTree0.insert((-1));
      int int1 = 0;
      aVLTree0.delete(0);
      aVLTree0.delete(4104);
      aVLTree0.height();
      aVLTree0.insert(3683);
      aVLTree0.height();
      AVLTree.Node aVLTree_Node0 = aVLTree0.getRoot();
      AVLTree.Node aVLTree_Node1 = aVLTree0.getRoot();
      aVLTree_Node1.height = 0;
      aVLTree_Node0.left = aVLTree_Node1;
      aVLTree_Node1.left = aVLTree_Node0.left;
      AVLTree.Node aVLTree_Node2 = aVLTree_Node0.right;
      aVLTree_Node0.left.left = aVLTree_Node1.left;
      aVLTree_Node2.left = aVLTree_Node0;
      aVLTree0.getBalance(aVLTree_Node2);
      // Undeclared exception!
      aVLTree0.delete(1759);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      AVLTree aVLTree0 = new AVLTree();
      int int0 = (-679);
      aVLTree0.delete((-679));
      aVLTree0.getRoot();
      AVLTree.Node aVLTree_Node0 = aVLTree0.find((-679));
      aVLTree0.insert(1);
      aVLTree0.delete(1);
      aVLTree0.height();
      aVLTree0.insert(0);
      AVLTree.Node aVLTree_Node1 = aVLTree0.find(0);
      AVLTree.Node aVLTree_Node2 = aVLTree0.getRoot();
      aVLTree_Node1.left = aVLTree_Node2;
      int int1 = 0;
      aVLTree0.delete(int0);
      aVLTree0.insert(int1);
      aVLTree_Node2.left = aVLTree_Node1.left;
      aVLTree_Node1.left = aVLTree_Node0;
      int int2 = 1634;
      aVLTree0.delete(int2);
      int int3 = 1646;
      aVLTree0.insert(int3);
      aVLTree0.height();
      aVLTree0.height();
      int int4 = aVLTree0.getBalance(aVLTree_Node1);
      aVLTree0.find(int4);
      int int5 = (-2064);
      aVLTree0.insert(int5);
      int int6 = (-1);
      aVLTree0.delete(int6);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      AVLTree aVLTree0 = new AVLTree();
      aVLTree0.insert(0);
      aVLTree0.insert(1);
      aVLTree0.insert(4034);
      aVLTree0.delete(554);
      aVLTree0.insert(1849);
      AVLTree.Node aVLTree_Node0 = aVLTree0.getRoot();
      aVLTree0.height();
      AVLTree.Node aVLTree_Node1 = aVLTree0.new Node((-382));
      aVLTree_Node0.left = aVLTree_Node1;
      aVLTree0.find(1);
      aVLTree0.height();
      aVLTree_Node1.left = aVLTree_Node0;
      aVLTree0.delete(1);
      aVLTree0.delete(673);
      aVLTree0.getRoot();
      aVLTree0.delete((-1650));
      aVLTree0.getBalance(aVLTree_Node0);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      AVLTree aVLTree0 = new AVLTree();
      aVLTree0.delete(0);
      aVLTree0.insert(0);
      aVLTree0.insert(2146);
      aVLTree0.delete(0);
      aVLTree0.insert(19);
      aVLTree0.delete(0);
      aVLTree0.delete(2514);
      aVLTree0.delete(0);
      aVLTree0.insert(1);
      aVLTree0.delete(2514);
      aVLTree0.delete((-875));
      aVLTree0.getBalance((AVLTree.Node) null);
      aVLTree0.insert(0);
      aVLTree0.height();
      aVLTree0.delete(0);
      aVLTree0.find(0);
      aVLTree0.insert(488);
      aVLTree0.delete(0);
      aVLTree0.find(2);
      aVLTree0.find(0);
      aVLTree0.getRoot();
      aVLTree0.find(1813);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      AVLTree aVLTree0 = new AVLTree();
      aVLTree0.delete((-1248));
      aVLTree0.delete((-3720));
      aVLTree0.delete(1);
      aVLTree0.delete(1);
      aVLTree0.insert((-1248));
      aVLTree0.insert(1);
      aVLTree0.insert(0);
      aVLTree0.insert((-1531));
      aVLTree0.find((-1248));
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      AVLTree aVLTree0 = new AVLTree();
      int int0 = 0;
      aVLTree0.delete(0);
      aVLTree0.delete(1429);
      aVLTree0.insert((-2669));
      aVLTree0.insert(0);
      aVLTree0.getRoot();
      // Undeclared exception!
      try { 
        aVLTree0.insert(0);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // duplicate Key!
         //
         verifyException("com.uh.pat.AVLTree", e);
      }
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      AVLTree aVLTree0 = new AVLTree();
      aVLTree0.height();
      aVLTree0.delete((-1));
      aVLTree0.insert(22);
      aVLTree0.delete((-1));
      aVLTree0.delete((-1));
      aVLTree0.getRoot();
      aVLTree0.insert((-1));
      int int0 = (-1);
      aVLTree0.insert(0);
      aVLTree0.find((-2750));
      aVLTree0.delete(1);
      // Undeclared exception!
      try { 
        aVLTree0.insert((-1));
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // duplicate Key!
         //
         verifyException("com.uh.pat.AVLTree", e);
      }
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      AVLTree aVLTree0 = new AVLTree();
      aVLTree0.insert((-1531));
      aVLTree0.find(0);
      aVLTree0.find((-1737));
  }
}
